### ISSUE TITLE
bug 规则导致贴吧吧内搜索乱码

### ISSUE THREAD

**Issue by aoguai** [JPLiu/TestFiles#1]
![image](https://github.com/user-attachments/assets/0c0966c8-905c-4b79-b2e0-5da7e120f460)

去掉规则 [`baidu.com^$removeparam=ie`](https://github.com/JPLiu/TestFiles/blob/442ae2000945957a80b2e49eeeab20f26f7d8898/Browser/uBlock-Origin/Liu's-Clear-List.list#L46C1-L46C28) 后正常

**Comment by JPLiu** [comment]
[d596411](https://github.com/JPLiu/TestFiles/commit/d596411d09f66607a026ff7e4828f3e4f6edafac) 已处理，感谢反馈。
