### ISSUE TITLE
内容农场屏蔽规则

### ISSUE THREAD

**Issue by H0wAway** [JPLiu/TestFiles#2]
格式为`||worktile.com^`的屏蔽规则，只能在点进网站的时候进行提醒。
![image](https://github.com/user-attachments/assets/d1507042-1f95-47a2-aff9-2f1567870dc9)
请问是否有一种 `uBlock Origin`规则，可以在搜索界面即可屏蔽该类网址呢？类似于`uBlacklist`插件的功能。
![image](https://github.com/user-attachments/assets/888ca717-0514-4a70-8b4d-0f69a5ab4b07)

**Comment by H0wAway** [comment]
已解决，参考项目：[ublock-origin-shitty-copies-filter](https://github.com/stroobants-dev/ublock-origin-shitty-copies-filter)

**Comment by JPLiu** [comment]
增加了一个 Content Farms Lite Hide 的规则（仅适配 Google），参考上面这个项目的 Google 部分规则。

https://github.com/JPLiu/TestFiles/blob/main/Browser/uBlock-Origin/More-Rule/Content-Farms-Lite-Hide.list

个人感觉命中率有点低，不如加一条百家号的规则影响大。
